apiVersion: v1
kind: Service
metadata:
  labels:
    app: landing-sales-frontend
  name: landing-sales-frontend
  namespace: applications
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: landing-sales-frontend
  sessionAffinity: None
  type: ClusterIP
